FROM python:3.9.12-slim

WORKDIR /usr/src/app

COPY requirements.txt requirements.txt
COPY models models
COPY dataset dataset
COPY train.py train.py

RUN pip install -r requirements.txt

ENTRYPOINT [ "python", "train.py" ]
