FROM python:3.9.12-slim

WORKDIR /usr/src/app

COPY requirements.txt requirements.txt
COPY models models
COPY dataset dataset
COPY inference.py inference.py
COPY data/*.json data/

RUN pip install -r requirements.txt

EXPOSE 8000

ENTRYPOINT [ "uvicorn", "inference:app", "--host", "0.0.0.0" ]